roll_offset: 3.053611653870123
pitch_offset: 0.0032841847230671295
yaw_offset: -1.6363553791994385
manual_roll_adjustment: 0.0
manual_pitch_adjustment: 0.0
manual_yaw_adjustment: 0.0
azimuth_offset: 0.0
elevation_offset: 0.0
x_offset: 0.12110228078994809
y_offset: 0.09188061460300538
z_offset: 0.06779759583561704
flip_x: false
flip_y: false
image_width: 1920
image_height: 960
use_fisheye: false
skip_rate: 5
