roll_offset: -3.114745986509006
pitch_offset: 0.035188793871230084
yaw_offset: -1.6087560653527575
manual_roll_adjustment: 0.0
manual_pitch_adjustment: 0.0
manual_yaw_adjustment: 0.0
azimuth_offset: 0.0
elevation_offset: 0.0
x_offset: 0.13884791603420746
y_offset: -0.01903411482041942
z_offset: 0.13848026260382057
flip_x: false
flip_y: false
image_width: 2560
image_height: 1280
use_fisheye: false
skip_rate: 5
