roll_offset: 3.1074476879353643
pitch_offset: -0.028162507203983278
yaw_offset: -1.6087476109692185
manual_roll_adjustment: 0.0
manual_pitch_adjustment: 0.0
manual_yaw_adjustment: 0.0
azimuth_offset: 0.0
elevation_offset: 0.0
x_offset: -0.008870577474302751
y_offset: 0.14314796265373952
z_offset: 0.1350844109740955
flip_x: false
flip_y: false
image_width: 3840
image_height: 1920
use_fisheye: false
skip_rate: 5
