roll_offset: 0.0
pitch_offset: 0.0
yaw_offset: 0.0
manual_roll_adjustment: 0.0
manual_pitch_adjustment: 0.0
manual_yaw_adjustment: 0.0
azimuth_offset: 0.0
elevation_offset: 0.0
x_offset: 0.0
y_offset: 0.0
z_offset: 0.0
flip_x: false
flip_y: false
image_width: 1920
image_height: 960
use_fisheye: false
skip_rate: 5
